[package]
name = "voda-db-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "parsing"] } 
quote = "1.0"
proc-macro2 = "1.0.95"
